sudo: false
language: rust
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
rust:
- nightly-2016-05-22
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH &&
  make toolchain
script:
- |
  make &&
  travis-cargo doc
after_success:
- travis-cargo doc-upload
- travis-cargo coveralls --no-sudo
env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - secure: CJkHS70fpCzY44romEAAnLjImniZ48G9lJmxB41sx51NGe22lfD4Sx/fVM88o/A3y/D+c9kWfE3F8c0h7ugO7uRe4u+2LZLigRj9t6F33la6YwkVvN3sQWCbAsFFQxeB5+srH0fvsQqUH5dWy+/OViIAk7tdrmB0WgJ52qDj17c=
